Language:
  - name: "Catala"
  - name: "Espa√±ol"
silaba:
  - silaba: "Monosil.labs"
silaba_un:
  - name: "Monosil.labs User 1"
    order: 1
    silaba_id: 1
  - name: "Monosil.labs User 2"
    order: 2
    silaba_id: 1
  - name: "Monosil.labs User 3"
    order: 3
    silaba_id: 1
  - name: "Monosil.labs User 4"
    order: 4
    silaba_id: 1
  - name: "Monosil.labs User 5"
    order: 5
    silaba_id: 1
silabs_user:
  - nom: "pa"
    owner_id: 1
    icon: "monosillab/bread.svg"
  - nom: "sol"
    owner_id: 1
    icon: "monosillab/bread.svg"
  - nom: "ou"
    owner_id: 1
    icon: "monosillab/bread.svg"
  - nom: "col"
    owner_id: 1
    icon: "monosillab/bread.svg"
  - nom: "ull"
    owner_id: 1
    icon: "monosillab/bread.svg"
